trigger: none
resources: 
  webhooks:
    - webhook: reprowebhook
      connection: FilterServiceConnection
      filters:
        - path: requestType
          value: a
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host ${{ convertToJson(parameters.reprowebhook.requestType) }}
      write-Host "Filter 1 pipeline with a value"
